$(SML_LIB)/basis/basis.mlb
ForLoop.sml
ifdef(`MEASURE',Measure.sml,MeasureDummy.sml)
Bit.sml
BIT_ARRAY.sig
BitArray.sml
BIT_VECTOR.sig
BitVector.sml
State.sml
StateArray.sml
Keccak.sml
Sha3Kind.sml
SHA3.sig
Sha3.sml
